---
version: '3.8'

networks:
  aspire-blog-network:

services:
  db:
    image: mongodb/mongodb-community-server:latest
    
    container_name: my-mongodb

    restart: always

    environment:
      - MONGO_INITDB_DATABASE=devblogposts
      - MONGO_INITDB_ROOT_USERNAME=course
      - MONGO_INITDB_ROOT_PASSWORD=whatever

    ports:
      - '27017:27017'

    networks:
      - aspire-blog-network