name: Publish Test Results

on:
  workflow_run:
    workflows: ["Build and Test .NET projects"]
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-results:
    name: Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      actions: read

    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@80620a5d27ce0ae443b965134db88467fc607b43
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
          
      - name: Install Python3
        run: python3 -m pip install --upgrade pip
          - 
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: 
            artifacts/**/*.trx
            artifacts/**/*.xml
            artifacts/**/*.js"