---
name: "Build and Test dev"

on:
  push:
    branches:
      - dev

    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

jobs:
  build-and-test:
    name: Build-and-Test=${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      BUILD_CONFIG: 'Release --no-restore'
      SOLUTION: 'AspireBlogApp.sln'
      REPORT_NAME: 'AspireBlogApp-Test-Results'
    
    steps:
      - uses: actions/checkout@v4
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow

      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./Global.json

      - name: Workload install
        run: dotnet workload restore

      - name: Restores
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG

      - name: Test
        run: dotnet test --configuration $BUILD_CONFIG --no-build --settings runsettings.xml

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.1
      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Codecov
        uses: codecov/codecov-action@v5.1.1

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPORT_NAME }}
          path: TestResults

        # Use always() to always run this step to
        # publish test results when there are test failures
        if: ${{ always() }}