name: Create GitHub Issues from TODOs, FIXMEs, etc.

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_run:
    workflows: ["Build and Test .NET projects"]
    branches: [main]
    types:
      - completed

jobs:
  create_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        # See https://github.com/marketplace/actions/todo-to-issue for more configuration options
        uses: "alstr/todo-to-issue-action@v5"
        with:
          IDENTIFIERS: '[{"name": "TODO", "labels": ["help wanted"]}, {"name": "FIXME", "labels": ["bug"]}]'